### ISSUE TITLE
Early Access Label does not appear. 

### ISSUE THREAD

**Issue by moonka** [georgevpanayotov/initiative_bot#2]
As seen in the screenshot below, when in use there is no label signifying the Early Access status of initiative bot.  

<img width="348" alt="Screenshot 2024-10-12 at 10 21 07 AM" src="https://github.com/user-attachments/assets/34f8a412-4836-42cd-abe2-038529a8946a">

**Comment by georgevpanayotov** [comment]
Won't fix. The design team doesn't like how this will look in the embed.
